#ifndef PKTLAB_DPDKD_VERSION_H
#define PKTLAB_DPDKD_VERSION_H

#define PKTLAB_DPDKD_SERVICE_NAME "pktlab-dpdkd"
#define PKTLAB_DPDKD_VERSION "0.1.0"
#define PKTLAB_DPDKD_DPDK_VERSION "25.11.0"

#endif /* PKTLAB_DPDKD_VERSION_H */
